# -*- coding: utf-8 -*-
message_1_minute = ["一分钟过去了", "已经过去一分钟啦", "小主人， 加油哦"]
message_2_minute = ["两分钟过去了", "已经过去两分钟啦", "小主人， 加油哦"]
message_3_minute = ["恭喜小主人，已经完成了三分钟预热"]
message_4_minute = ["四分钟过去了", "已经过去四分钟啦", "小主人， 加油哦"]
message_5_minute = ["五分钟过去了", "已经过去五分钟啦", "小主人， 加油哦"]
message_6_minute = ["控制呼吸，掌握好节奏"]
message_7_minute = ["七分钟过去了", "已经过去七分钟啦", "小主人， 加油哦"]
message_8_minute = ["有没有感觉到渐入佳境？加油加油"]
message_9_minute = ["九分钟过去了", "已经过去九分钟啦", "小主人， 加油哦"]
message_10_minute = ["小主人，再接再厉呀", "再坚持十分钟"]
message_11_minute = ["十一分钟过去了", "已经过去十一分钟啦", "小主人，坚持就是胜利"]
message_12_minute = ["十二分钟过去了", "已经过去十二分钟啦", "小主人，坚持就是胜利"]
message_13_minute = ["十三分钟过去了", "已经过去十三分钟啦", "小主人，坚持就是胜利"]
message_14_minute = ["十四分钟过去了", "已经过去十四分钟啦", "小主人，坚持就是胜利"]
message_15_minute = ["坚持一下，最后五分钟"]
message_16_minute = ["十六分钟过去了", "已经过去十六分钟啦", "小主人，坚持就是胜利"]
message_17_minute = ["加油，再坚持三分钟"]
message_18_minute = ["加油，再坚持两分钟"]
message_19_minute = ["加油加油，最后一分钟"]
message_20_minute = ["主人好棒，已经完成了今天的训练"]
message = [message_1_minute, message_2_minute, message_3_minute, message_4_minute, message_5_minute, message_6_minute,
           message_7_minute, message_8_minute, message_9_minute, message_10_minute, message_11_minute, message_12_minute,
           message_13_minute, message_14_minute, message_15_minute, message_16_minute, message_17_minute, message_18_minute,
           message_19_minute, message_20_minute]